### ISSUE TITLE
Code Request

### ISSUE THREAD

**Issue by zoule41** [CityU-AIM-Group/MRM#1]
Hello. I have read your work and find it very inspiring. I want to try reproducing your code. 
I wonder if you could provide the code file for me to learn and reference? Thanks.

**Comment by IcecreamArtist** [comment]
me too

**Comment by sebastianffx** [comment]
Thanks for the intention of uploading the code! 
Do you have any estimates of when the code will be available @QiushiYang ?

Thanks!

**Comment by QiushiYang** [comment]
Thanks a lot for your attention on our work. I am recently preparing the journal version of this work, and plan to release source codes after the journal revision. 

The main implementation of the core idea, i.e., relation masking, is very simple. You can firstly try to apply the element-wise masking on attention maps to improve the pre-training of MAEs on your tasks.

**Comment by QiushiYang** [comment]
Thanks for your attention on our work. We are recently preparing the journal version of this work, and plan to release source codes after the journal revision. 
The main implementation of the core idea, i.e., relation masking, is very simple. You can firstly try to apply the element-wsie masking on attention maps to improve the pre-training of MAEs on your tasks.
