### ISSUE TITLE
Request for Source Code

### ISSUE THREAD

**Issue by yusijin02** [CityU-AIM-Group/MRM#2]
Dear Authors,

I am highly intrigued by your proposed MRM concept, and I look forward to seeing the implementation in code! It has been some time since the conclusion of ICCV 2023, and I was wondering if you might consider releasing the source code soon? Additionally, if there are any preview or beta versions of the source code available, I would be very interested in accessing them. Thank you for your consideration!

**Comment by QiushiYang** [comment]
Thanks for your attention on our work. I am recently preparing the journal version of this work, and plan to release source codes after the journal revision. 
The main implementation of the core idea, i.e., relation masking, is very simple. You can firstly try to apply the element-wsie masking on attention maps to improve the pre-training of MAEs on your tasks.

**Comment by QiushiYang** [comment]
Thanks for your attention on our work. We are recently preparing the journal version of this work, and plan to release source codes after the journal revision. 
\
The main implementation of the core idea, i.e., relation masking, is very simple. You can firstly try to apply the element-wsie masking on attention maps to improve the pre-training of MAEs on your tasks.
